AWSTemplateFormatVersion: '2010-09-09'
Description: 'ANB Rising Stars - Amazon SQS Queue for Video Processing'

Parameters:
  EnvironmentName:
    Description: Environment name prefix (must match other stacks)
    Type: String
    Default: anb-production

  MessageRetentionPeriod:
    Description: Message retention period in seconds (1 min to 14 days)
    Type: Number
    Default: 345600  # 4 days
    MinValue: 60
    MaxValue: 1209600

  VisibilityTimeout:
    Description: Visibility timeout in seconds (should be > processing time)
    Type: Number
    Default: 900  # 15 minutes
    MinValue: 0
    MaxValue: 43200

  MaxReceiveCount:
    Description: Max number of times a message can be received before being sent to DLQ
    Type: Number
    Default: 3
    MinValue: 1
    MaxValue: 1000

Resources:
  # Dead Letter Queue (DLQ) para mensajes que fallan repetidamente
  VideoProcessingDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${EnvironmentName}-video-processing-dlq'
      MessageRetentionPeriod: 1209600  # 14 días
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-video-processing-dlq'
        - Key: Environment
          Value: !Ref EnvironmentName

  # Cola principal de procesamiento de videos
  VideoProcessingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${EnvironmentName}-video-processing'
      MessageRetentionPeriod: !Ref MessageRetentionPeriod
      VisibilityTimeout: !Ref VisibilityTimeout
      ReceiveMessageWaitTimeSeconds: 20  # Long polling
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt VideoProcessingDLQ.Arn
        maxReceiveCount: !Ref MaxReceiveCount
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-video-processing'
        - Key: Environment
          Value: !Ref EnvironmentName

  # CloudWatch Alarms para monitorear la cola
  QueueDepthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${EnvironmentName}-sqs-queue-depth-high'
      AlarmDescription: Alert when queue depth is high
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 100  # Alarma si hay más de 100 mensajes pendientes
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt VideoProcessingQueue.QueueName

  OldestMessageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${EnvironmentName}-sqs-message-age-high'
      AlarmDescription: Alert when oldest message age is high
      MetricName: ApproximateAgeOfOldestMessage
      Namespace: AWS/SQS
      Statistic: Maximum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1800  # 30 minutos
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt VideoProcessingQueue.QueueName

  DLQDepthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${EnvironmentName}-sqs-dlq-messages'
      AlarmDescription: Alert when messages appear in DLQ
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt VideoProcessingDLQ.QueueName

Outputs:
  QueueURL:
    Description: URL of the SQS Queue
    Value: !Ref VideoProcessingQueue
    Export:
      Name: !Sub '${EnvironmentName}-SQSQueueURL'

  QueueARN:
    Description: ARN of the SQS Queue
    Value: !GetAtt VideoProcessingQueue.Arn
    Export:
      Name: !Sub '${EnvironmentName}-SQSQueueARN'

  QueueName:
    Description: Name of the SQS Queue
    Value: !GetAtt VideoProcessingQueue.QueueName
    Export:
      Name: !Sub '${EnvironmentName}-SQSQueueName'

  DLQURL:
    Description: URL of the Dead Letter Queue
    Value: !Ref VideoProcessingDLQ
    Export:
      Name: !Sub '${EnvironmentName}-SQSDLQURL'

  DLQARN:
    Description: ARN of the Dead Letter Queue
    Value: !GetAtt VideoProcessingDLQ.Arn
    Export:
      Name: !Sub '${EnvironmentName}-SQSDLQARN'
